service: serverless-test
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-1
  memorySize: 2048
  timeout: 10

functions:
  hello:
    handler: handler.hello
    timeout: 30
    events:
      - http: 
          path: /{proxy+}
          method: any